kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: m2-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  quarkus-sync-demo-tilt
spec:
  selector:
    matchLabels:
      app:  quarkus-sync-demo-tilt
  template:
    metadata:
      labels:
        app:  quarkus-sync-demo-tilt
    spec:
      containers:
        - name:  quarkus-sync-demo-tilt
          image: quarkus-sync-image-tilt
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-web
              containerPort: 8080
            - name: jdwp-debug
              containerPort: 5005  
          volumeMounts:
            - mountPath: /.m2
              name: m2-cache
            - mountPath: /project/target
              name: target-cache
      volumes:
        - name: m2-cache
          persistentVolumeClaim:
            claimName: m2-cache
        - name: target-cache
          emptyDir: {}
